{
 "title": "Common-wall",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "repeat": "Host" },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "invoice_payment_event.status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "span_id",
       "id": 1,
       "meta": {},
       "pipelineAgg": "cardinality",
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND NOT invoice_payment_event.status:processed",
     "timeField": "@timestamp"
    },
    {
     "alias": "Created invoices",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_event.id.keyword",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND invoice_event.type:\"invoice_created\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IPM 10m avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_event.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND invoice_event.type:\"invoice_created\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PPM 10m avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:hellgate AND NOT invoice_payment_event.status:processed",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PPM 10m max",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:hellgate AND NOT invoice_payment_event.status:processed",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failed PPM 10m avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:hellgate AND NOT invoice_payment_event.status:failed ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PPM 24h ago",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:hellgate AND invoice_payment_event.status:captured",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Test PPM avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:hellgate AND invoice_payment_event.status:captured AND invoice_payment_event.invoice.owner_id:\"281220eb-a4ef-4d03-b666-bdec4b26c5f7\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "RBKmoney test payments",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_payment_event.invoice.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND invoice_payment_event.status:captured AND invoice_payment_event.invoice.owner_id:\"281220eb-a4ef-4d03-b666-bdec4b26c5f7\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Invoices",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_event.id.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND invoice_event.type:\"invoice_created\" AND invoice_event.owner_id:\"281220eb-a4ef-4d03-b666-bdec4b26c5f7\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Total captured",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_payment_event.invoice.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND invoice_payment_event.status:captured AND invoice_payment_event.invoice.owner_id:\"281220eb-a4ef-4d03-b666-bdec4b26c5f7\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top merchants payments",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ECP captured",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_payment_event.invoice.id",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "rpc.server.metadata.user-identity.id=\"157d515e-d4d2-4251-b3b1-dc6dc291f9e5\" AND kubernetes.pod.name:hellgate AND invoice_payment_event.status:captured",
     "timeField": "@timestamp"
    },
    {
     "alias": "S2P captured",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_payment_event.invoice.id",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "rpc.server.metadata.user-identity.id=\"ecd62927-e643-4f24-878f-51186164c5c1\" AND kubernetes.pod.name:hellgate AND invoice_payment_event.status:captured",
     "timeField": "@timestamp"
    },
    {
     "alias": "PayC captured",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_payment_event.invoice.id",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "rpc.server.metadata.user-identity.id=\"84f1f881-5305-4796-8dbe-34a9c110dc58\" AND kubernetes.pod.name:hellgate AND invoice_payment_event.status:captured",
     "timeField": "@timestamp"
    },
    {
     "alias": "Other captured",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_payment_event.invoice.id",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND invoice_payment_event.status:captured AND NOT rpc.server.metadata.user-identity.id:(\"84f1f881-5305-4796-8dbe-34a9c110dc58\" OR \"ecd62927-e643-4f24-878f-51186164c5c1\" OR \"157d515e-d4d2-4251-b3b1-dc6dc291f9e5\" OR \"39214738-cdaa-467a-9c20-163a98dc0ad6\")",
     "timeField": "@timestamp"
    },
    {
     "alias": "Okko captured",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_payment_event.invoice.id",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate  AND invoice_payment_event.status:captured  AND rpc.server.metadata.user-identity.id:(\"39214738-cdaa-467a-9c20-163a98dc0ad6\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Java Kafka consumer lag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_length",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "count"
      }
     ],
     "query": "log.file.path:\"/var/lib/docker/conteiners/\" AND status:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Payment errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "invoice_payment_event.error",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "9" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "span_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND  invoice_payment_event.type:invoice_payment_status_changed AND  invoice_payment_event.status:failed",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Proxy/adapter success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{term service.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "service.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_length",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(/(proxy|adapter|provider)-.*/ OR service:antifraud) AND message:PaymentProxyResult AND message:\"success:Success()\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HG warnings and errors ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "HG {{term @severity.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "@severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:hellgate AND (@severity:warning OR @severity:error)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Proxy/adapter/provider errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "service.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(/(proxy|adapter|provider)-.*/ OR service:antifraud) AND @severity:ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hooker responses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Response",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:hooker AND logger_name:\"com.rbkmoney.hooker.service.PostSender\" AND message:\"Response from hook\" AND message:200",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CreateInvoice timings",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "80",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "kubernetes.pod.name:capi AND operation_id:CreateInvoice AND (status:[200 TO 299] or status:[500 TO 599])",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.pod.name:capi AND operation_id:CreateInvoice AND (status:[200 TO 299] or status:[500 TO 599])",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CreatePayment timings",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "80",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "kubernetes.pod.name:capi AND operation_id:CreatePayment AND (status:[200 TO 299] or status:[500 TO 599])",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.pod.name:capi AND operation_id:CreatePayment AND (status:[200 TO 299] or status:[500 TO 599])",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CreatePaymentResource timings",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operation_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "80",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "kubernetes.pod.name:capi AND operation_id:CreatePaymentResource AND (status:[200 TO 299] or status:[500 TO 599])",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operation_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.pod.name:capi AND operation_id:CreatePaymentResource AND (status:[200 TO 299] or status:[500 TO 599])",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GetInvoiceEvents timings",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "80",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "kubernetes.pod.name:capi AND operation_id:GetInvoiceEvents AND (status:[200 TO 299] or status:[500 TO 599])",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.pod.name:capi AND operation_id:GetInvoiceEvents AND (status:[200 TO 299] or status:[500 TO 599])",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GetPaymentByID timings",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "80",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "kubernetes.pod.name:capi AND operation_id:GetPaymentByID AND (status:[200 TO 299] or status:[500 TO 599])",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.pod.name:capi AND operation_id:GetPaymentByID AND (status:[200 TO 299] or status:[500 TO 599])",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MG machine fails",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "machine_ns.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:machinegun AND @severity:error AND message:\"machine failed\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Machine fails 24h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:machinegun AND @severity:error AND \"machine failed\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Invoice fails 24h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 35 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:machinegun AND @severity:error AND \"machine failed\" AND machine_ns.keyword:invoice",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Uniq fails 24h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "machine_id.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:machinegun AND @severity:error AND \"machine failed\" AND machine_ns.keyword:invoice",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MG warnings and errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "MG {{term @severity.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "@severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:machinegun AND (@severity:warning OR @severity:error)",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "LBS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Completed requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "log.file.path:\"/var/lib/docker/containers/\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "2xx by http_host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http_host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "log.file.path:\"/var/lib/docker/containers/\" AND status:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "5xx by http_host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "http_host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "log.file.path:\"/var/lib/docker/conteiners/\" AND status:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Requests by balancer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "log.file.path:\"/var/lib/docker/containers/\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "429 by http_host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http_host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "log.file.path:\"/var/lib/docker/containers/\" AND status:429",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "429 by remote_addr",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "remote_addr.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "log.file.path:\"/var/lib/docker/containers/\" AND status:429",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Auth 2xx request time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http_host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "75",
         "90",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "log.file.path:\"/var/lib/docker/containers/\" AND (http_host:auth.rbk.money) AND (status:[200 TO 299])",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API 2xx request time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http_host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "75",
         "90",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "log.file.path:\"/var/lib/docker/containers/\" AND (http_host:api.rbk.money) AND (status:[200 TO 299])",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "wrapper 2xx request time ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http_host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "75",
         "90",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "log.file.path:\"/var/lib/docker/containers/\" AND (http_host:wrapper.rbk.money) AND (status:[200 TO 299])",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Other 2xx request time ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http_host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "75",
         "90",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "log.file.path:\"/var/lib/docker/containers/\" AND (http_host:rbk.mn OR http_host:storage.rbk.money) AND (status:[200 TO 299])",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "CAPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "2xx on CAPI",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operation_id",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "9" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "service.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:capi AND status:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "5xx on CAPI",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:capi AND status:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CAPI operation_id top",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operation_id",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "9" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:capi",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "2xx on CAPI by host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "service.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:capi AND status:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CreateInvoice timings by host ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "95" ] },
       "type": "percentiles"
      }
     ],
     "query": "kubernetes.pod.name:capi AND operation_id:CreateInvoice AND status:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CreatePayment timings by host ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "95" ] },
       "type": "percentiles"
      }
     ],
     "query": "kubernetes.pod.name:capi AND operation_id:CreatePayment AND status:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "5xx on CAPI by host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "service.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:capi AND status:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CAPI operation_id request_time top",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operation_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "9" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "kubernetes.pod.name:capi and status:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CreatePaymentResource time by host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "95" ] },
       "type": "percentiles"
      }
     ],
     "query": "kubernetes.pod.name:capi AND (operation_id:CreatePaymentResource) AND status:[200 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Hellgate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Hellgate top rpc.server.function",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "rpc.server.function.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "9" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "span_id",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hellgate top rpc.server.function",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "rpc.server.function.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "9" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "span_id",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HG cache miss by host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "9" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "span_id",
       "id": "3",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "rpc.caching_client.service:PartyManagement AND rpc.caching_client.function:Checkout AND rpc.caching_client.event:\"client cache miss\" AND rpc.client.event:\"call service\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}