{
 "title": "Demo Demo for team",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Host", "query": "collectd.*" }
  ]
 },
 "panels": [
  { "title": "$Host", "type": "row", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "repeat": "Host" },
  {
   "title": "5min load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "collectd.$Host.load.load.midterm"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 10, "x": 10, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "target": "collectd.$Host.uptime.uptime" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(exclude(collectd.$Host.cpu-*.cpu-*, \"idle\"), 3, \"sumSeries\"), 2)"
    },
    {
     "target": "alias(sumSeries(exclude(collectd.$Host.aggregation-cpu-average.cpu-*, \"idle\")), \"average\")"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$Host.memory.memory-cached, 'Cached')"
    },
    {
     "target": "alias(collectd.$Host.memory.memory-free, 'Free')"
    },
    {
     "target": "alias(collectd.$Host.memory.memory-used, 'Used')"
    }
   ]
  },
  {
   "title": "Balancers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 30, "x": 10, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_length",
       "id": 1,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service:\"capi\" AND NOT request_path:\"/health\" AND status:[100 TO 599]",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_length",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "count"
      }
     ],
     "query": "source:\"/var/log/nginx/macroservice_access.json\" AND NOT request_path:\"/health\" AND http_host:\"api.rbk.money\" AND status:[100 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}