{
 "title": "Machinegun Namespace Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "K8S Namespace",
    "query": "label_values(erlang_vm_process_count, namespace)"
   },
   {
    "name": "mg_namespace",
    "label": "MG Namespace",
    "query": "label_values(mg_machine_lifecycle_changes_total{namespace=\"$namespace\"}, exported_namespace)"
   },
   { "name": "service", "label": "Service", "query": "machinegun" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(erlang_vm_process_count{namespace=\"$namespace\", service=\"$service\"}, pod)"
   },
   {
    "name": "scheduler",
    "label": "Scheduler Name",
    "query": "label_values(mg_scheduler_task_changes_total{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\"}, name)"
   },
   {
    "name": "storage",
    "label": "Storage Name",
    "query": "label_values(mg_storage_operation_changes_total{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\"}, name)"
   },
   {
    "name": "storage_operation",
    "label": "Storage Operation Name",
    "query": "label_values(mg_storage_operation_changes_total{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\"}, operation)"
   },
   {
    "name": "riak_pool",
    "label": "Riak Pool Name",
    "query": "label_values(mg_riak_pool_connections_in_use{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\"}, name)"
   },
   {
    "name": "processing_impact",
    "label": "Processing Impact",
    "query": "label_values(mg_machine_processing_changes_total{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\"}, impact)"
   }
  ]
 },
 "panels": [
  { "title": "`[[mg_namespace]]` Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Timers Lifecycle",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (change)(irate(mg_timer_lifecycle_changes_total{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\"}[$interval]))",
     "legendFormat": "{{change}}"
    }
   ]
  },
  {
   "title": "Machines Process Impact",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (impact)(irate(mg_machine_processing_changes_total{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", change=\"started\"}[$interval]))",
     "legendFormat": "{{impact}}"
    }
   ]
  },
  {
   "title": "Machines Lifecycle",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (change)(irate(mg_machine_lifecycle_changes_total{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\"}[$interval]))",
     "legendFormat": "{{change}}"
    }
   ]
  },
  {
   "title": "Machines Start Queue Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le)(mg_worker_action_queue_usage_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\"}))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(mg_worker_action_queue_usage_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\"}))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(mg_worker_action_queue_usage_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\"}))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "BEAM on [[pod]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "pod" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "irate(erlang_vm_statistics_runtime_milliseconds{namespace=\"$namespace\", pod=\"$pod\"}[$interval]) / on (namespace, pod) irate(erlang_vm_statistics_wallclock_time_milliseconds[$interval])",
     "legendFormat": "BEAM CPU Time"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "Pod CPU Time"
    },
    {
     "expr": "max(irate(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=\"$pod\", container=\"\"}[$interval]) / on (namespace, pod, container, node, service) irate(container_cpu_cfs_periods_total[$interval]))",
     "legendFormat": "CPU Throttling"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_context_switches{namespace=\"$namespace\", pod=\"$pod\"}[$interval])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "irate(erlang_vm_statistics_reductions_total{namespace=\"$namespace\", pod=\"$pod\"}[$interval])",
     "legendFormat": "Reductions"
    }
   ]
  },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_number_of_gcs{namespace=\"$namespace\", pod=\"$pod\"}[$interval])",
     "legendFormat": "Number of GCs"
    },
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_bytes_reclaimed{namespace=\"$namespace\", pod=\"$pod\"}[$interval])",
     "legendFormat": "Bytes Reclaimed"
    }
   ]
  },
  {
   "title": "Pod Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Memory Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum(erlang_vm_memory_system_bytes_total{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "BEAM Total"
    },
    {
     "expr": "max(container_memory_rss{namespace=\"$namespace\", pod=\"$pod\", container=\"\"})",
     "legendFormat": "Pod RSS"
    },
    {
     "expr": "max(container_memory_cache{namespace=\"$namespace\", pod=\"$pod\", container=\"\"})",
     "legendFormat": "Pod Cache"
    },
    {
     "expr": "max(container_memory_usage_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"\"})",
     "legendFormat": "Pod Usage"
    }
   ]
  },
  {
   "title": "IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_bytes_received_total{namespace=\"$namespace\", pod=\"$pod\"}[$interval])",
     "legendFormat": "Input"
    },
    {
     "expr": "-irate(erlang_vm_statistics_bytes_output_total{namespace=\"$namespace\", pod=\"$pod\"}[$interval])",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_process_count{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Processes"
    },
    {
     "expr": "erlang_vm_statistics_run_queues_length_total{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Run Queues Length"
    }
   ]
  },
  {
   "title": "`[[scheduler]]` Scheduler Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "scheduler",
   "collapsed": true,
   "panels": [
    {
     "title": "Tasks",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (change)(irate(mg_scheduler_task_changes_total{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$scheduler\"}[$interval]))",
       "legendFormat": "{{change}}"
      }
     ]
    },
    {
     "title": "Scan Delay",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le)(mg_scheduler_scan_delay_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$scheduler\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le)(mg_scheduler_scan_delay_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$scheduler\"}))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le)(mg_scheduler_scan_delay_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$scheduler\"}))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Task Delay",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le)(mg_scheduler_task_processing_delay_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$scheduler\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le)(mg_scheduler_task_processing_delay_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$scheduler\"}))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le)(mg_scheduler_task_processing_delay_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$scheduler\"}))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Quota Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (status)(mg_scheduler_task_quota_usage{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$scheduler\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Scan Duration",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le)(mg_scheduler_scan_duration_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$scheduler\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le)(mg_scheduler_scan_duration_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$scheduler\"}))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le)(mg_scheduler_scan_duration_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$scheduler\"}))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Task Processing Duration",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le)(mg_scheduler_task_processing_duration_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$scheduler\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le)(mg_scheduler_task_processing_duration_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$scheduler\"}))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le)(mg_scheduler_task_processing_duration_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$scheduler\"}))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  {
   "title": "`[[storage]]` Storage Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "storage",
   "collapsed": true,
   "panels": [
    {
     "title": "`[[storage_operation]]` Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
     "repeat": "storage_operation",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (change)(irate(mg_storage_operation_changes_total{change=\"finish\", namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$storage\", operation=\"$storage_operation\"}[$interval]))",
       "legendFormat": "finished"
      },
      {
       "expr": "sum by (change)(irate(mg_storage_operation_changes_total{change=\"finish\", namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$storage\", operation=\"$storage_operation\"}[$interval])) - sum by (change)(irate(mg_storage_operation_changes_total{change=\"start\", namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$storage\", operation=\"$storage_operation\"}[$interval]))",
       "legendFormat": "not finished"
      }
     ]
    },
    {
     "title": "`[[storage_operation]]` Duration",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
     "repeat": "storage_operation",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le)(mg_storage_operation_duration_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$storage\", operation=\"$storage_operation\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le)(mg_storage_operation_duration_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$storage\", operation=\"$storage_operation\"}))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le)(mg_storage_operation_duration_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$storage\", operation=\"$storage_operation\"}))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  {
   "title": "`[[riak_pool]]` Riak Pool Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "riak_pool",
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(mg_riak_pool_connections_in_use{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"})",
       "legendFormat": "in use"
      },
      {
       "expr": "sum(mg_riak_pool_connections_free{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"})",
       "legendFormat": "free"
      },
      {
       "expr": "sum(mg_riak_pool_connections_limit{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "In Use Connections Per Request",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le)(mg_riak_pool_connections_in_use_per_request_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le)(mg_riak_pool_connections_in_use_per_request_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"}))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le)(mg_riak_pool_connections_in_use_per_request_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"}))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Queued Requests Per Request",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le)(mg_riak_pool_queued_requests_per_request_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le)(mg_riak_pool_queued_requests_per_request_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"}))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le)(mg_riak_pool_queued_requests_per_request_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"}))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Connect Timeout Errors Number",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(mg_riak_pool_connect_timeout_errors_total{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"}[$interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Killed Free Connections Number",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(mg_riak_pool_killed_free_connections_total{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"}[$interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Pool Queue",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(mg_riak_pool_queued_requests{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"})",
       "legendFormat": "queued"
      },
      {
       "expr": "sum(mg_riak_pool_queued_requests_limit{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Free Connections Per Request",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le)(mg_riak_pool_connections_free_per_request_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le)(mg_riak_pool_connections_free_per_request_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"}))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le)(mg_riak_pool_connections_free_per_request_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"}))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "No Free Connection Errors Number",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(mg_riak_pool_no_free_connection_errors_total{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"}[$interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Queue Limit Reached Errors Number",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(mg_riak_pool_queue_limit_reached_errors_total{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"}[$interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Killed In Use Connections Number",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(mg_riak_pool_killed_in_use_connections_total{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", name=\"$riak_pool\"}[$interval]))",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "`[[processing_impact]]` Impact Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "processing_impact",
   "collapsed": true,
   "panels": [
    {
     "title": "Machine Processing Started",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(mg_machine_processing_changes_total{change=\"started\", namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", impact=\"$processing_impact\"}[$interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Machine Processing Duration",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le)(mg_machine_processing_duration_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", impact=\"$processing_impact\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le)(mg_machine_processing_duration_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", impact=\"$processing_impact\"}))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le)(mg_machine_processing_duration_seconds_bucket{namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", impact=\"$processing_impact\"}))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Machine Processing Finished",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(mg_machine_processing_changes_total{change=\"finished\", namespace=\"$namespace\", exported_namespace=\"$mg_namespace\", impact=\"$processing_impact\"}[$interval]))",
       "legendFormat": "total"
      }
     ]
    }
   ]
  }
 ]
}