{
 "title": "Riak KV / CDS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "collectd.riak-cd*" }
  ]
 },
 "panels": [
  { "title": "summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "vnode_index_reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-vnode_index_reads, '.*(cd[0-9]).*(vnode_index_reads.*)', '\\1 \\2')"
    }
   ]
  },
  {
   "title": "node_gets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-node_gets, '.*(cd[0-9]).*(node_gets.*)', '\\1 \\2')"
    }
   ]
  },
  {
   "title": "vnode_gets_total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.counter-vnode_gets_total, '.*(cd[0-9]).*(vnode_gets_total.*)', '\\1 \\2')"
    }
   ]
  },
  {
   "title": "pbc_active",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-pbc_active, '.*(cd[0-9]).*(pbc_active.*)', '\\1 \\2')"
    }
   ]
  },
  {
   "title": "vnode_index_writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-vnode_index_writes, '.*(cd[0-9]).*(vnode_index_writes.*)', '\\1 \\2')"
    }
   ]
  },
  {
   "title": "node_puts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-node_puts, '.*(cd[0-9]).*(node_puts.*)', '\\1 \\2')"
    }
   ]
  },
  {
   "title": "vnode_puts_total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.counter-vnode_puts_total, '.*(cd[0-9]).*(vnode_puts_total.*)', '\\1 \\2')"
    }
   ]
  },
  { "title": "gets @ node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-node_gets, '.*(cd[0-9]).*(node_gets.*)', '\\1 \\2')"
    },
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-node_get_fsm_time_99, '.*(cd[0-9]).*get_fsm_(time_.*)', '\\1 \\2')"
    },
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-node_get_fsm_time_95, '.*(cd[0-9]).*get_fsm_(time_.*)', '\\1 \\2')"
    },
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-node_get_fsm_time_mean, '.*(cd[0-9]).*get_fsm_(time_.*)', '\\1 \\2')"
    }
   ]
  },
  { "title": "puts @ node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 50 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-node_puts, '.*(cd[0-9]).*(node_puts.*)', '\\1 \\2')"
    },
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-node_put_fsm_time_99, '.*(cd[0-9]).*put_fsm_(time_.*)', '\\1 \\2')"
    },
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-node_put_fsm_time_95, '.*(cd[0-9]).*put_fsm_(time_.*)', '\\1 \\2')"
    },
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-node_put_fsm_time_mean, '.*(cd[0-9]).*put_fsm_(time_.*)', '\\1 \\2')"
    }
   ]
  },
  { "title": "objsize @ node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 64 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-node_get_fsm_objsize_100, '.*(cd[0-9]).*get_fsm_(objsize_.*)', '\\1 \\2')"
    },
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-node_get_fsm_objsize_99, '.*(cd[0-9]).*get_fsm_(objsize_.*)', '\\1 \\2')"
    },
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-node_get_fsm_objsize_median, '.*(cd[0-9]).*get_fsm_(objsize_.*)', '\\1 \\2')"
    }
   ]
  },
  { "title": "pb connections @ node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 91 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(collectd.$instance.curl_json-riak.gauge-pbc_active, '.*(cd[0-9]).*(pbc_active.*)', '\\1 \\2')"
    }
   ]
  }
 ]
}