{
 "title": "Thrift call timings",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Invoicing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Automaton.GetMachine",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Invoicing\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"GetMachine\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Invoicing\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"GetMachine\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Automaton.Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Invoicing\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"Call\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Invoicing\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"Call\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Automaton.Start",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Invoicing\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"Start\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Invoicing\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"Start\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PartyManagement.GetRevision",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Invoicing\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"PartyManagement\" AND rpc.client.function.keyword:\"GetRevision\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Invoicing\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"PartyManagement\" AND rpc.client.function.keyword:\"GetRevision\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PartyManagement.Checkout",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Invoicing\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"PartyManagement\" AND rpc.client.function.keyword:\"Checkout\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Invoicing\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"PartyManagement\" AND rpc.client.function.keyword:\"Checkout\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Hellgate processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "PartyManagement.GetRevision",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"PartyManagement\" AND rpc.client.function.keyword:\"GetRevision\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"PartyManagement\" AND rpc.client.function.keyword:\"GetRevision\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PartyManagement.Checkout",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"PartyManagement\" AND rpc.client.function.keyword:\"Checkout\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"PartyManagement\" AND rpc.client.function.keyword:\"Checkout\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PartyManagement.ComputeContractTerms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"PartyManagement\" AND rpc.client.function.keyword:\"ComputeContractTerms\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"PartyManagement\" AND rpc.client.function.keyword:\"ComputeContractTerms\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PartyManagement.ComputeProvider",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"PartyManagement\" AND rpc.client.function.keyword:\"ComputeProvider\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"PartyManagement\" AND rpc.client.function.keyword:\"ComputeProvider\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Accounter.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Accounter\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Accounter\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PartyManagement.ComputeProviderTerminalTerms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"PartyManagement\" AND rpc.client.function.keyword:\"ComputeProviderTerminalTerms\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"PartyManagement\" AND rpc.client.function.keyword:\"ComputeProviderTerminalTerms\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "InspectorProxy.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"InspectorProxy\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"InspectorProxy\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ProviderProxy.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"ProviderProxy\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"ProviderProxy\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "FaultDetector.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"FaultDetector\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"Processor\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"FaultDetector\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Bender", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Automaton.GetMachine",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"bender\" AND rpc.server.service.keyword:\"Bender\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"GetMachine\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"bender\" AND rpc.server.service.keyword:\"Bender\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"GetMachine\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Automaton.Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"bender\" AND rpc.server.service.keyword:\"Bender\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"Call\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"bender\" AND rpc.server.service.keyword:\"Bender\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"Call\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Automaton.Start",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"bender\" AND rpc.server.service.keyword:\"Bender\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"Start\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"bender\" AND rpc.server.service.keyword:\"Bender\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"Start\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "CAPI v2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Bender.GenerateID",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Bender\" AND rpc.client.function.keyword:\"GenerateID\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Bender\" AND rpc.client.function.keyword:\"GenerateID\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bender.GetInternalID",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Bender\" AND rpc.client.function.keyword:\"GetInternalID\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Bender\" AND rpc.client.function.keyword:\"GetInternalID\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Invoicing.Create",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Invoicing\" AND rpc.client.function.keyword:\"Create\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Invoicing\" AND rpc.client.function.keyword:\"Create\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Invoicing.CreateWithTemplate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Invoicing\" AND rpc.client.function.keyword:\"CreateWithTemplate\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Invoicing\" AND rpc.client.function.keyword:\"CreateWithTemplate\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Invoicing.GetEvents",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Invoicing\" AND rpc.client.function.keyword:\"GetEvents\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Invoicing\" AND rpc.client.function.keyword:\"GetEvents\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Invoicing.Get",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Invoicing\" AND rpc.client.function.keyword:\"Get\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Invoicing\" AND rpc.client.function.keyword:\"Get\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Invoicing.StartPayment",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Invoicing\" AND rpc.client.function.keyword:\"StartPayment\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Invoicing\" AND rpc.client.function.keyword:\"StartPayment\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "InvoiceTemplating.ComputeTerms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"InvoiceTemplating\" AND rpc.client.function.keyword:\"ComputeTerms\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"InvoiceTemplating\" AND rpc.client.function.keyword:\"ComputeTerms\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Invoicing.ComputeTerms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Invoicing\" AND rpc.client.function.keyword:\"ComputeTerms\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"capi-v2\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Invoicing\" AND rpc.client.function.keyword:\"ComputeTerms\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "CAPI v2 PCI-DSS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Bender.GenerateID",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"capi-v2-pcidss\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Bender\" AND rpc.client.function.keyword:\"GenerateID\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"capi-v2-pcidss\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Bender\" AND rpc.client.function.keyword:\"GenerateID\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bender.GetInternalID",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"capi-v2-pcidss\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Bender\" AND rpc.client.function.keyword:\"GetInternalID\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"capi-v2-pcidss\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Bender\" AND rpc.client.function.keyword:\"GetInternalID\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CDS.PutCard",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"capi-v2-pcidss\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Storage\" AND rpc.client.function.keyword:\"PutCard\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"capi-v2-pcidss\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Storage\" AND rpc.client.function.keyword:\"PutCard\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CDS.PutSession",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"capi-v2-pcidss\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Storage\" AND rpc.client.function.keyword:\"PutSession\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"capi-v2-pcidss\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Storage\" AND rpc.client.function.keyword:\"PutSession\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Binbase.Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"capi-v2-pcidss\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Binbase\" AND rpc.client.function.keyword:\"Lookup\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"capi-v2-pcidss\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Binbase\" AND rpc.client.function.keyword:\"Lookup\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "PartyManagement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "Automaton.GetMachine",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"PartyManagement\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"GetMachine\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"PartyManagement\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"GetMachine\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Automaton.Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"PartyManagement\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"Call\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"PartyManagement\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"Call\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Accounter.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"PartyManagement\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Accounter\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"PartyManagement\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Accounter\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Automaton.Start",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"PartyManagement\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"Start\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"hellgate\" AND rpc.server.service.keyword:\"PartyManagement\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Automaton\" AND rpc.client.function.keyword:\"Start\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Machinegun", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "Processor.ProcessSignal",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"machinegun\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Processor\" AND rpc.client.function.keyword:\"ProcessSignal\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"machinegun\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Processor\" AND rpc.client.function.keyword:\"ProcessSignal\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processor.ProcessCall",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "50",
         "95",
         "98"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "service.keyword:\"machinegun\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Processor\" AND rpc.client.function.keyword:\"ProcessCall\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rpc.client.execution_duration_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:\"machinegun\" AND rpc.client.event:\"service result\"  AND rpc.client.service.keyword:\"Processor\" AND rpc.client.function.keyword:\"ProcessCall\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}