{
 "title": "TV2-processing",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Real payments",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "invoice_payment_event.status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "span_id",
       "id": 1,
       "meta": {},
       "pipelineAgg": "cardinality",
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND NOT invoice_payment_event.status:processed",
     "timeField": "@timestamp"
    },
    {
     "alias": "Created invoices",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_event.id.keyword",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND invoice_event.type:\"invoice_created\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Proxy/adapter/provider errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_length",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "count"
      }
     ],
     "query": "/(proxy|adapter|provider)-.*/ AND @severity:ERROR",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_length",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "count"
      }
     ],
     "query": "service.keyword:antifraud AND @severity:ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MG machine fails",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "machine_ns.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:machinegun AND @severity:error AND message:\"machine failed\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "5xx on CAPI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "service.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "operation_id.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:capi AND status:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "RBKmoney test payments",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_payment_event.invoice.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND invoice_payment_event.status:captured AND invoice_payment_event.invoice.owner_id:\"281220eb-a4ef-4d03-b666-bdec4b26c5f7\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Invoices",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_event.id.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND invoice_event.type:\"invoice_created\" AND invoice_event.owner_id:\"281220eb-a4ef-4d03-b666-bdec4b26c5f7\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Total captured",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_payment_event.invoice.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND invoice_payment_event.status:captured AND invoice_payment_event.invoice.owner_id:\"281220eb-a4ef-4d03-b666-bdec4b26c5f7\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Payment errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "invoice_payment_event.error",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "9" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "span_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND  invoice_payment_event.type:invoice_payment_status_changed AND  invoice_payment_event.status:failed",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MG timers created",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_length",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND invoice_event.type:\"invoice_created\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Java Kafka consumer lag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_length",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "count"
      }
     ],
     "query": "log.file.path:\"/var/lib/docker/conteiners/\" AND status:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "5xx by http_host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_length",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "count"
      }
     ],
     "query": "log.file.path:\"/var/lib/docker/conteiners/\" AND status:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Completed requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "log.file.path:\"/var/lib/docker/containers/\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IPM avg",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "invoice_event.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.pod.name:hellgate AND invoice_event.type:\"invoice_created\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PPM avg",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:hellgate AND NOT invoice_payment_event.status:processed",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HTTP 502 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source:\"/var/lib/docker/containers\" AND status:502",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HTTP 504 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source:\"/var/lib/docker/containers\" AND status:504",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Invoice fails 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:machinegun AND @severity:error AND \"machine failed\" AND machine_ns.keyword:invoice",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Other machine fails 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod.name:machinegun AND @severity:error AND \"machine failed\" AND NOT machine_ns.keyword:invoice",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}